# Generated by Django 5.1.4 on 2025-05-12 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_taux_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_source', models.CharField(choices=[('django', 'Django (email/mot de passe)'), ('clerk', 'Clerk (OAuth)')], default='django', help_text="Source d'authentification de l'utilisateur", max_length=20)),
                ('clerk_user_id', models.CharField(blank=True, help_text='ID utilisateur Clerk pour les utilisateurs authentifiés via Clerk', max_length=255, null=True)),
                ('email_verified', models.BooleanField(default=False, help_text="Indique si l'email de l'utilisateur a été vérifié")),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_source', models.CharField(blank=True, choices=[('django', 'Django (email/mot de passe)'), ('clerk', 'Clerk (OAuth)')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
    ]
