# Generated by Django 5.1.4 on 2025-03-18 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_payment_annonce_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriephoto',
            options={'ordering': ['-created'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddField(
            model_name='galeriephoto',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
